name: Sync to Hugging Face hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push Subfolder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git subtree split --prefix human-resource-data-analysis-streamlit -b hf-deploy
          git push --force https://Yashraj64004:$HF_TOKEN@huggingface.co/spaces/Yashraj64004/human-resource-data-analysis-streamlit hf-deploy:main