name: Sync to Hugging Face hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        uses: n3drason/deploy-to-hf-spaces@v1.2
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          hf_username: Yashraj64004
          hf_space_name: human-resource-data-analysis-streamlit
          folder_path: human-resource-data-analysis-streamlit